[build]
  publish = "public"
  command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "https://beat-wave.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200